// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Options that change functionality of a sink exporting data to BigQuery.
public struct BigQueryOptions: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. Whether to use [BigQuery's partition
  /// tables](https://cloud.google.com/bigquery/docs/partitioned-tables). By
  /// default, Cloud Logging creates dated tables based on the log entries'
  /// timestamps, e.g. syslog_20170523. With partitioned tables the date suffix
  /// is no longer present and [special query
  /// syntax](https://cloud.google.com/bigquery/docs/querying-partitioned-tables)
  /// has to be used instead. In both cases, tables are sharded based on UTC
  /// timezone.
  public var usePartitionedTables: Swift.Bool = Swift.Bool()

  /// Output only. True if new timestamp column based partitioning is in use,
  /// false if legacy ingestion-time partitioning is in use.
  ///
  /// All new sinks will have this field set true and will use timestamp column
  /// based partitioning. If use_partitioned_tables is false, this value has no
  /// meaning and will be false. Legacy sinks using partitioned tables will have
  /// this field set to false.
  public var usesTimestampColumnPartitioning: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `BigQueryOptions`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BigQueryOptions().with { $0.usePartitionedTables = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let usePartitionedTables = CodingKeys(stringValue: "usePartitionedTables")
    static let usesTimestampColumnPartitioning = CodingKeys(
      stringValue: "usesTimestampColumnPartitioning")

    static let _knownKeys: Set<Swift.String> = [
      "usePartitionedTables",
      "usesTimestampColumnPartitioning",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .usePartitionedTables) {
      self.usePartitionedTables = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .usesTimestampColumnPartitioning)
    {
      self.usesTimestampColumnPartitioning = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.usePartitionedTables, forKey: .usePartitionedTables)
    try container.encode(
      self.usesTimestampColumnPartitioning, forKey: .usesTimestampColumnPartitioning)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.logging.v2.BigQueryOptions"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
