// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Metadata for LongRunningUpdateBucket Operations.
public struct BucketMetadata: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The create time of an operation.
  public var startTime: GoogleWKT.Timestamp? = nil

  /// The end time of an operation.
  public var endTime: GoogleWKT.Timestamp? = nil

  /// State of an operation.
  public var state: OperationState = OperationState()

  public var request: OneOf_Request? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `BucketMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BucketMetadata().with { $0.startTime = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let startTime = CodingKeys(stringValue: "startTime")
    static let endTime = CodingKeys(stringValue: "endTime")
    static let state = CodingKeys(stringValue: "state")
    static let createBucketRequest = CodingKeys(stringValue: "createBucketRequest")
    static let updateBucketRequest = CodingKeys(stringValue: "updateBucketRequest")

    static let _knownKeys: Set<Swift.String> = [
      "startTime",
      "endTime",
      "state",
      "createBucketRequest",
      "updateBucketRequest",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.startTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .startTime)
    self.endTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .endTime)
    if let value = try container.decodeIfPresent(OperationState.self, forKey: .state) {
      self.state = value
    }

    var request: OneOf_Request? = nil
    let requestCheckAndSet = {
      if request != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'request'"))
      }
      request = $0
    }
    if let createBucketRequest = try container.decodeIfPresent(
      CreateBucketRequest?.self, forKey: .createBucketRequest)
    {
      try requestCheckAndSet(.createBucketRequest(createBucketRequest))
    }
    if let updateBucketRequest = try container.decodeIfPresent(
      UpdateBucketRequest?.self, forKey: .updateBucketRequest)
    {
      try requestCheckAndSet(.updateBucketRequest(updateBucketRequest))
    }
    self.request = request
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.startTime, forKey: .startTime)
    try container.encodeIfPresent(self.endTime, forKey: .endTime)
    try container.encode(self.state, forKey: .state)

    if let choice = self.request {
      switch choice {
      case .createBucketRequest(let value):
        try container.encode(value, forKey: .createBucketRequest)
      case .updateBucketRequest(let value):
        try container.encode(value, forKey: .updateBucketRequest)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public enum OneOf_Request: Codable, Equatable, Sendable {
    /// LongRunningCreateBucket RPC request.
    indirect case createBucketRequest(CreateBucketRequest?)
    /// LongRunningUpdateBucket RPC request.
    indirect case updateBucketRequest(UpdateBucketRequest?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.logging.v2.BucketMetadata"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
