// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

extension Clients {
  protocol ConfigServiceV2Stub {
    func listBuckets(
      request: ListBucketsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.ListBucketsResponse

    func getBucket(
      request: GetBucketRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.LogBucket

    func createBucketAsync(
      request: CreateBucketRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateBucketAsync(
      request: UpdateBucketRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func createBucket(
      request: CreateBucketRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.LogBucket

    func updateBucket(
      request: UpdateBucketRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.LogBucket

    func deleteBucket(
      request: DeleteBucketRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func undeleteBucket(
      request: UndeleteBucketRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func listViews(
      request: ListViewsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.ListViewsResponse

    func getView(
      request: GetViewRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.LogView

    func createView(
      request: CreateViewRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.LogView

    func updateView(
      request: UpdateViewRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.LogView

    func deleteView(
      request: DeleteViewRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func listSinks(
      request: ListSinksRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.ListSinksResponse

    func getSink(
      request: GetSinkRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.LogSink

    func createSink(
      request: CreateSinkRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.LogSink

    func updateSink(
      request: UpdateSinkRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.LogSink

    func deleteSink(
      request: DeleteSinkRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func createLink(
      request: CreateLinkRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteLink(
      request: DeleteLinkRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listLinks(
      request: ListLinksRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.ListLinksResponse

    func getLink(
      request: GetLinkRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.Link

    func listExclusions(
      request: ListExclusionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.ListExclusionsResponse

    func getExclusion(
      request: GetExclusionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.LogExclusion

    func createExclusion(
      request: CreateExclusionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.LogExclusion

    func updateExclusion(
      request: UpdateExclusionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.LogExclusion

    func deleteExclusion(
      request: DeleteExclusionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func getCmekSettings(
      request: GetCmekSettingsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.CmekSettings

    func updateCmekSettings(
      request: UpdateCmekSettingsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.CmekSettings

    func getSettings(
      request: GetSettingsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.Settings

    func updateSettings(
      request: UpdateSettingsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.Settings

    func copyLogEntries(
      request: CopyLogEntriesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}
