// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax
import struct Logging.Logger

extension Clients {
  final class ConfigServiceV2Logging: ConfigServiceV2Stub {
    let inner: any ConfigServiceV2Stub
    let logger: Logger

    public init(_ inner: any ConfigServiceV2Stub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-logging-v2"
      logger[metadataKey: "gcp.client.service"] = "logging"
      logger[metadataKey: "gcp.experimental.swift.client"] = "ConfigServiceV2"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listBuckets(
      request: ListBucketsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.ListBucketsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listBuckets",
        action: {
          (r: ListBucketsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLoggingV2.ListBucketsResponse
          in
          return try await self.inner.listBuckets(request: r, options: o)
        })
    }

    public func getBucket(
      request: GetBucketRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.LogBucket {
      try await self._intercept(
        request: request,
        options: options,
        name: "getBucket",
        action: {
          (r: GetBucketRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLoggingV2.LogBucket
          in
          return try await self.inner.getBucket(request: r, options: o)
        })
    }

    public func createBucketAsync(
      request: CreateBucketRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createBucketAsync",
        action: {
          (r: CreateBucketRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createBucketAsync(request: r, options: o)
        })
    }

    public func updateBucketAsync(
      request: UpdateBucketRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateBucketAsync",
        action: {
          (r: UpdateBucketRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateBucketAsync(request: r, options: o)
        })
    }

    public func createBucket(
      request: CreateBucketRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.LogBucket {
      try await self._intercept(
        request: request,
        options: options,
        name: "createBucket",
        action: {
          (r: CreateBucketRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLoggingV2.LogBucket
          in
          return try await self.inner.createBucket(request: r, options: o)
        })
    }

    public func updateBucket(
      request: UpdateBucketRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.LogBucket {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateBucket",
        action: {
          (r: UpdateBucketRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLoggingV2.LogBucket
          in
          return try await self.inner.updateBucket(request: r, options: o)
        })
    }

    public func deleteBucket(
      request: DeleteBucketRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteBucket",
        action: { (r: DeleteBucketRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteBucket(request: r, options: o)
        })
    }

    public func undeleteBucket(
      request: UndeleteBucketRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "undeleteBucket",
        action: { (r: UndeleteBucketRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.undeleteBucket(request: r, options: o)
        })
    }

    public func listViews(
      request: ListViewsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.ListViewsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listViews",
        action: {
          (r: ListViewsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLoggingV2.ListViewsResponse
          in
          return try await self.inner.listViews(request: r, options: o)
        })
    }

    public func getView(
      request: GetViewRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.LogView {
      try await self._intercept(
        request: request,
        options: options,
        name: "getView",
        action: {
          (r: GetViewRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLoggingV2.LogView
          in
          return try await self.inner.getView(request: r, options: o)
        })
    }

    public func createView(
      request: CreateViewRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.LogView {
      try await self._intercept(
        request: request,
        options: options,
        name: "createView",
        action: {
          (r: CreateViewRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLoggingV2.LogView
          in
          return try await self.inner.createView(request: r, options: o)
        })
    }

    public func updateView(
      request: UpdateViewRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.LogView {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateView",
        action: {
          (r: UpdateViewRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLoggingV2.LogView
          in
          return try await self.inner.updateView(request: r, options: o)
        })
    }

    public func deleteView(
      request: DeleteViewRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteView",
        action: { (r: DeleteViewRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteView(request: r, options: o)
        })
    }

    public func listSinks(
      request: ListSinksRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.ListSinksResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listSinks",
        action: {
          (r: ListSinksRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLoggingV2.ListSinksResponse
          in
          return try await self.inner.listSinks(request: r, options: o)
        })
    }

    public func getSink(
      request: GetSinkRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.LogSink {
      try await self._intercept(
        request: request,
        options: options,
        name: "getSink",
        action: {
          (r: GetSinkRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLoggingV2.LogSink
          in
          return try await self.inner.getSink(request: r, options: o)
        })
    }

    public func createSink(
      request: CreateSinkRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.LogSink {
      try await self._intercept(
        request: request,
        options: options,
        name: "createSink",
        action: {
          (r: CreateSinkRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLoggingV2.LogSink
          in
          return try await self.inner.createSink(request: r, options: o)
        })
    }

    public func updateSink(
      request: UpdateSinkRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.LogSink {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateSink",
        action: {
          (r: UpdateSinkRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLoggingV2.LogSink
          in
          return try await self.inner.updateSink(request: r, options: o)
        })
    }

    public func deleteSink(
      request: DeleteSinkRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteSink",
        action: { (r: DeleteSinkRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteSink(request: r, options: o)
        })
    }

    public func createLink(
      request: CreateLinkRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createLink",
        action: {
          (r: CreateLinkRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createLink(request: r, options: o)
        })
    }

    public func deleteLink(
      request: DeleteLinkRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteLink",
        action: {
          (r: DeleteLinkRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteLink(request: r, options: o)
        })
    }

    public func listLinks(
      request: ListLinksRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.ListLinksResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLinks",
        action: {
          (r: ListLinksRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLoggingV2.ListLinksResponse
          in
          return try await self.inner.listLinks(request: r, options: o)
        })
    }

    public func getLink(
      request: GetLinkRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.Link {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLink",
        action: {
          (r: GetLinkRequest, o: GoogleGax.RequestOptions) async throws -> GoogleCloudLoggingV2.Link
          in
          return try await self.inner.getLink(request: r, options: o)
        })
    }

    public func listExclusions(
      request: ListExclusionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.ListExclusionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listExclusions",
        action: {
          (r: ListExclusionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLoggingV2.ListExclusionsResponse
          in
          return try await self.inner.listExclusions(request: r, options: o)
        })
    }

    public func getExclusion(
      request: GetExclusionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.LogExclusion {
      try await self._intercept(
        request: request,
        options: options,
        name: "getExclusion",
        action: {
          (r: GetExclusionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLoggingV2.LogExclusion
          in
          return try await self.inner.getExclusion(request: r, options: o)
        })
    }

    public func createExclusion(
      request: CreateExclusionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.LogExclusion {
      try await self._intercept(
        request: request,
        options: options,
        name: "createExclusion",
        action: {
          (r: CreateExclusionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLoggingV2.LogExclusion
          in
          return try await self.inner.createExclusion(request: r, options: o)
        })
    }

    public func updateExclusion(
      request: UpdateExclusionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.LogExclusion {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateExclusion",
        action: {
          (r: UpdateExclusionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLoggingV2.LogExclusion
          in
          return try await self.inner.updateExclusion(request: r, options: o)
        })
    }

    public func deleteExclusion(
      request: DeleteExclusionRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteExclusion",
        action: { (r: DeleteExclusionRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteExclusion(request: r, options: o)
        })
    }

    public func getCmekSettings(
      request: GetCmekSettingsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.CmekSettings {
      try await self._intercept(
        request: request,
        options: options,
        name: "getCmekSettings",
        action: {
          (r: GetCmekSettingsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLoggingV2.CmekSettings
          in
          return try await self.inner.getCmekSettings(request: r, options: o)
        })
    }

    public func updateCmekSettings(
      request: UpdateCmekSettingsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.CmekSettings {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateCmekSettings",
        action: {
          (r: UpdateCmekSettingsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLoggingV2.CmekSettings
          in
          return try await self.inner.updateCmekSettings(request: r, options: o)
        })
    }

    public func getSettings(
      request: GetSettingsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.Settings {
      try await self._intercept(
        request: request,
        options: options,
        name: "getSettings",
        action: {
          (r: GetSettingsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLoggingV2.Settings
          in
          return try await self.inner.getSettings(request: r, options: o)
        })
    }

    public func updateSettings(
      request: UpdateSettingsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.Settings {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateSettings",
        action: {
          (r: UpdateSettingsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLoggingV2.Settings
          in
          return try await self.inner.updateSettings(request: r, options: o)
        })
    }

    public func copyLogEntries(
      request: CopyLogEntriesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "copyLogEntries",
        action: {
          (r: CopyLogEntriesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.copyLogEntries(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOperation",
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
