// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Metadata for CopyLogEntries long running operations.
public struct CopyLogEntriesMetadata: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The create time of an operation.
  public var startTime: GoogleCloudWkt.Timestamp? = nil

  /// The end time of an operation.
  public var endTime: GoogleCloudWkt.Timestamp? = nil

  /// State of an operation.
  public var state: OperationState = OperationState()

  /// Identifies whether the user has requested cancellation of the operation.
  public var cancellationRequested: Swift.Bool = Swift.Bool()

  /// CopyLogEntries RPC request.
  public var request: CopyLogEntriesRequest? = nil

  /// Estimated progress of the operation (0 - 100%).
  public var progress: Swift.Int32 = Swift.Int32()

  /// The IAM identity of a service account that must be granted access to the
  /// destination.
  ///
  /// If the service account is not granted permission to the destination within
  /// an hour, the operation will be cancelled.
  ///
  /// For example: `"serviceAccount:foo@bar.com"`
  public var writerIdentity: Swift.String = Swift.String()

  /// Initialize a new instance of `CopyLogEntriesMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CopyLogEntriesMetadata().with { $0.startTime = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.logging.v2.CopyLogEntriesMetadata"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
