// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The parameters to `CreateView`.
public struct CreateViewRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The bucket in which to create the view
  ///
  ///     `"projects/[PROJECT_ID]/locations/[LOCATION_ID]/buckets/[BUCKET_ID]"`
  ///
  /// For example:
  ///
  ///   `"projects/my-project/locations/global/buckets/my-bucket"`
  public var parent: Swift.String = Swift.String()

  /// Required. A client-assigned identifier such as `"my-view"`. Identifiers are
  /// limited to 100 characters and can include only letters, digits,
  /// underscores, hyphens, and periods.
  public var viewId: Swift.String = Swift.String()

  /// Required. The new view.
  public var view: LogView? = nil

  /// Initialize a new instance of `CreateViewRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateViewRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.logging.v2.CreateViewRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
