// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The parameters to `CreateSink`.
public struct CreateSinkRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The resource in which to create the sink:
  ///
  ///     "projects/[PROJECT_ID]"
  ///     "organizations/[ORGANIZATION_ID]"
  ///     "billingAccounts/[BILLING_ACCOUNT_ID]"
  ///     "folders/[FOLDER_ID]"
  ///
  /// For examples:
  ///
  ///   `"projects/my-project"`
  ///   `"organizations/123456789"`
  public var parent: Swift.String = Swift.String()

  /// Required. The new sink, whose `name` parameter is a sink identifier that
  /// is not already in use.
  public var sink: LogSink? = nil

  /// Optional. Determines the kind of IAM identity returned as `writer_identity`
  /// in the new sink. If this value is omitted or set to false, and if the
  /// sink's parent is a project, then the value returned as `writer_identity` is
  /// the same group or service account used by Cloud Logging before the addition
  /// of writer identities to this API. The sink's destination must be in the
  /// same project as the sink itself.
  ///
  /// If this field is set to true, or if the sink is owned by a non-project
  /// resource such as an organization, then the value of `writer_identity` will
  /// be a unique service account used only for exports from the new sink. For
  /// more information, see `writer_identity` in
  /// [LogSink][google.logging.v2.LogSink].
  ///
  /// [google.logging.v2.LogSink]: <doc:LogSink>
  public var uniqueWriterIdentity: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `CreateSinkRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateSinkRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.logging.v2.CreateSinkRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
