// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// The parameters to `CreateSink`.
public struct CreateSinkRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The resource in which to create the sink:
  ///
  ///     "projects/[PROJECT_ID]"
  ///     "organizations/[ORGANIZATION_ID]"
  ///     "billingAccounts/[BILLING_ACCOUNT_ID]"
  ///     "folders/[FOLDER_ID]"
  ///
  /// For examples:
  ///
  ///   `"projects/my-project"`
  ///   `"organizations/123456789"`
  public var parent: Swift.String = Swift.String()

  /// Required. The new sink, whose `name` parameter is a sink identifier that
  /// is not already in use.
  public var sink: LogSink? = nil

  /// Optional. Determines the kind of IAM identity returned as `writer_identity`
  /// in the new sink. If this value is omitted or set to false, and if the
  /// sink's parent is a project, then the value returned as `writer_identity` is
  /// the same group or service account used by Cloud Logging before the addition
  /// of writer identities to this API. The sink's destination must be in the
  /// same project as the sink itself.
  ///
  /// If this field is set to true, or if the sink is owned by a non-project
  /// resource such as an organization, then the value of `writer_identity` will
  /// be a unique service account used only for exports from the new sink. For
  /// more information, see `writer_identity` in
  /// [LogSink][google.logging.v2.LogSink].
  ///
  /// [google.logging.v2.LogSink]: <doc:LogSink>
  public var uniqueWriterIdentity: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CreateSinkRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateSinkRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let sink = CodingKeys(stringValue: "sink")
    static let uniqueWriterIdentity = CodingKeys(stringValue: "uniqueWriterIdentity")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "sink",
      "uniqueWriterIdentity",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    self.sink = try container.decodeIfPresent(LogSink.self, forKey: .sink)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .uniqueWriterIdentity) {
      self.uniqueWriterIdentity = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encodeIfPresent(self.sink, forKey: .sink)
    try container.encode(self.uniqueWriterIdentity, forKey: .uniqueWriterIdentity)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.logging.v2.CreateSinkRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
