// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The parameters to DeleteLog.
public struct DeleteLogRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The resource name of the log to delete:
  ///
  /// * `projects/[PROJECT_ID]/logs/[LOG_ID]`
  /// * `organizations/[ORGANIZATION_ID]/logs/[LOG_ID]`
  /// * `billingAccounts/[BILLING_ACCOUNT_ID]/logs/[LOG_ID]`
  /// * `folders/[FOLDER_ID]/logs/[LOG_ID]`
  ///
  /// `[LOG_ID]` must be URL-encoded. For example,
  /// `"projects/my-project-id/logs/syslog"`,
  /// `"organizations/123/logs/cloudaudit.googleapis.com%2Factivity"`.
  ///
  /// For more information about log names, see
  /// [LogEntry][google.logging.v2.LogEntry].
  ///
  /// [google.logging.v2.LogEntry]: <doc:LogEntry>
  public var logName: Swift.String = Swift.String()

  /// Initialize a new instance of `DeleteLogRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DeleteLogRequest().with { $0.logName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.logging.v2.DeleteLogRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
