// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Describes a link connected to an analytics enabled bucket.
public struct Link: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The resource name of the link. The name can have up to 100 characters.
  /// A valid link id (at the end of the link name) must only have alphanumeric
  /// characters and underscores within it.
  ///
  ///     "projects/[PROJECT_ID]/locations/[LOCATION_ID]/buckets/[BUCKET_ID]/links/[LINK_ID]"
  ///     "organizations/[ORGANIZATION_ID]/locations/[LOCATION_ID]/buckets/[BUCKET_ID]/links/[LINK_ID]"
  ///     "billingAccounts/[BILLING_ACCOUNT_ID]/locations/[LOCATION_ID]/buckets/[BUCKET_ID]/links/[LINK_ID]"
  ///     "folders/[FOLDER_ID]/locations/[LOCATION_ID]/buckets/[BUCKET_ID]/links/[LINK_ID]"
  ///
  /// For example:
  ///
  ///   `projects/my-project/locations/global/buckets/my-bucket/links/my_link
  public var name: Swift.String = Swift.String()

  /// Describes this link.
  ///
  /// The maximum length of the description is 8000 characters.
  public var description: Swift.String = Swift.String()

  /// Output only. The creation timestamp of the link.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The resource lifecycle state.
  public var lifecycleState: LifecycleState = LifecycleState()

  /// The information of a BigQuery Dataset. When a link is created, a BigQuery
  /// dataset is created along with it, in the same project as the LogBucket it's
  /// linked to. This dataset will also have BigQuery Views corresponding to the
  /// LogViews in the bucket.
  public var bigqueryDataset: BigQueryDataset? = nil

  /// Initialize a new instance of `Link`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Link().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.logging.v2.Link"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
