// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Describes a link connected to an analytics enabled bucket.
public struct Link: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The resource name of the link. The name can have up to 100 characters.
  /// A valid link id (at the end of the link name) must only have alphanumeric
  /// characters and underscores within it.
  ///
  ///     "projects/[PROJECT_ID]/locations/[LOCATION_ID]/buckets/[BUCKET_ID]/links/[LINK_ID]"
  ///     "organizations/[ORGANIZATION_ID]/locations/[LOCATION_ID]/buckets/[BUCKET_ID]/links/[LINK_ID]"
  ///     "billingAccounts/[BILLING_ACCOUNT_ID]/locations/[LOCATION_ID]/buckets/[BUCKET_ID]/links/[LINK_ID]"
  ///     "folders/[FOLDER_ID]/locations/[LOCATION_ID]/buckets/[BUCKET_ID]/links/[LINK_ID]"
  ///
  /// For example:
  ///
  ///   `projects/my-project/locations/global/buckets/my-bucket/links/my_link
  public var name: Swift.String = Swift.String()

  /// Describes this link.
  ///
  /// The maximum length of the description is 8000 characters.
  public var description: Swift.String = Swift.String()

  /// Output only. The creation timestamp of the link.
  public var createTime: GoogleWKT.Timestamp? = nil

  /// Output only. The resource lifecycle state.
  public var lifecycleState: LifecycleState = LifecycleState()

  /// The information of a BigQuery Dataset. When a link is created, a BigQuery
  /// dataset is created along with it, in the same project as the LogBucket it's
  /// linked to. This dataset will also have BigQuery Views corresponding to the
  /// LogViews in the bucket.
  public var bigqueryDataset: BigQueryDataset? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Link`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Link().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let description = CodingKeys(stringValue: "description")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let lifecycleState = CodingKeys(stringValue: "lifecycleState")
    static let bigqueryDataset = CodingKeys(stringValue: "bigqueryDataset")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "description",
      "createTime",
      "lifecycleState",
      "bigqueryDataset",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    self.createTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .createTime)
    if let value = try container.decodeIfPresent(LifecycleState.self, forKey: .lifecycleState) {
      self.lifecycleState = value
    }
    self.bigqueryDataset = try container.decodeIfPresent(
      BigQueryDataset.self, forKey: .bigqueryDataset)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.description, forKey: .description)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encode(self.lifecycleState, forKey: .lifecycleState)
    try container.encodeIfPresent(self.bigqueryDataset, forKey: .bigqueryDataset)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.logging.v2.Link"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
