// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Result returned from ListLogs.
public struct ListLogsResponse: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// A list of log names. For example,
  /// `"projects/my-project/logs/syslog"` or
  /// `"organizations/123/logs/cloudresourcemanager.googleapis.com%2Factivity"`.
  public var logNames: [Swift.String] = []

  /// If there might be more results than those appearing in this response, then
  /// `nextPageToken` is included.  To get the next set of results, call this
  /// method again using the value of `nextPageToken` as `pageToken`.
  public var nextPageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `ListLogsResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListLogsResponse().with { $0.logNames = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.logging.v2.ListLogsResponse"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
