// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// The parameters to ListMonitoredResourceDescriptors
public struct ListMonitoredResourceDescriptorsRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. The maximum number of results to return from this request.
  /// Non-positive values are ignored.  The presence of `nextPageToken` in the
  /// response indicates that more results might be available.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. If present, then retrieve the next batch of results from the
  /// preceding call to this method.  `pageToken` must be the value of
  /// `nextPageToken` from the previous response.  The values of other method
  /// parameters should be identical to those in the previous call.
  public var pageToken: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ListMonitoredResourceDescriptorsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListMonitoredResourceDescriptorsRequest().with { $0.pageSize = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let pageSize = CodingKeys(stringValue: "pageSize")
    static let pageToken = CodingKeys(stringValue: "pageToken")

    static let _knownKeys: Set<Swift.String> = [
      "pageSize",
      "pageToken",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .pageSize) {
      self.pageSize = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .pageToken) {
      self.pageToken = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.pageSize, forKey: .pageSize)
    try container.encode(self.pageToken, forKey: .pageToken)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.logging.v2.ListMonitoredResourceDescriptorsRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
