// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Describes a repository in which log entries are stored.
public struct LogBucket: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The resource name of the bucket.
  ///
  /// For example:
  ///
  ///   `projects/my-project/locations/global/buckets/my-bucket`
  ///
  /// For a list of supported locations, see [Supported
  /// Regions](https://cloud.google.com/logging/docs/region-support)
  ///
  /// For the location of `global` it is unspecified where log entries are
  /// actually stored.
  ///
  /// After a bucket has been created, the location cannot be changed.
  public var name: Swift.String = Swift.String()

  /// Describes this bucket.
  public var description: Swift.String = Swift.String()

  /// Output only. The creation timestamp of the bucket. This is not set for any
  /// of the default buckets.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The last update timestamp of the bucket.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Logs will be retained by default for this amount of time, after which they
  /// will automatically be deleted. The minimum retention period is 1 day. If
  /// this value is set to zero at bucket creation time, the default time of 30
  /// days will be used.
  public var retentionDays: Swift.Int32 = Swift.Int32()

  /// Whether the bucket is locked.
  ///
  /// The retention period on a locked bucket cannot be changed. Locked buckets
  /// may only be deleted if they are empty.
  public var locked: Swift.Bool = Swift.Bool()

  /// Output only. The bucket lifecycle state.
  public var lifecycleState: LifecycleState = LifecycleState()

  /// Whether log analytics is enabled for this bucket.
  ///
  /// Once enabled, log analytics features cannot be disabled.
  public var analyticsEnabled: Swift.Bool = Swift.Bool()

  /// Log entry field paths that are denied access in this bucket.
  ///
  /// The following fields and their children are eligible: `textPayload`,
  /// `jsonPayload`, `protoPayload`, `httpRequest`, `labels`, `sourceLocation`.
  ///
  /// Restricting a repeated field will restrict all values. Adding a parent will
  /// block all child fields. (e.g. `foo.bar` will block `foo.bar.baz`)
  public var restrictedFields: [Swift.String] = []

  /// A list of indexed fields and related configuration data.
  public var indexConfigs: [IndexConfig] = []

  /// The CMEK settings of the log bucket. If present, new log entries written to
  /// this log bucket are encrypted using the CMEK key provided in this
  /// configuration. If a log bucket has CMEK settings, the CMEK settings cannot
  /// be disabled later by updating the log bucket. Changing the KMS key is
  /// allowed.
  public var cmekSettings: CmekSettings? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `LogBucket`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LogBucket().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let description = CodingKeys(stringValue: "description")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let retentionDays = CodingKeys(stringValue: "retentionDays")
    static let locked = CodingKeys(stringValue: "locked")
    static let lifecycleState = CodingKeys(stringValue: "lifecycleState")
    static let analyticsEnabled = CodingKeys(stringValue: "analyticsEnabled")
    static let restrictedFields = CodingKeys(stringValue: "restrictedFields")
    static let indexConfigs = CodingKeys(stringValue: "indexConfigs")
    static let cmekSettings = CodingKeys(stringValue: "cmekSettings")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "description",
      "createTime",
      "updateTime",
      "retentionDays",
      "locked",
      "lifecycleState",
      "analyticsEnabled",
      "restrictedFields",
      "indexConfigs",
      "cmekSettings",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .retentionDays) {
      self.retentionDays = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .locked) {
      self.locked = value
    }
    if let value = try container.decodeIfPresent(LifecycleState.self, forKey: .lifecycleState) {
      self.lifecycleState = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .analyticsEnabled) {
      self.analyticsEnabled = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .restrictedFields) {
      self.restrictedFields = value
    }
    if let value = try container.decodeIfPresent([IndexConfig].self, forKey: .indexConfigs) {
      self.indexConfigs = value
    }
    self.cmekSettings = try container.decodeIfPresent(CmekSettings.self, forKey: .cmekSettings)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.description, forKey: .description)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.retentionDays, forKey: .retentionDays)
    try container.encode(self.locked, forKey: .locked)
    try container.encode(self.lifecycleState, forKey: .lifecycleState)
    try container.encode(self.analyticsEnabled, forKey: .analyticsEnabled)
    try container.encode(self.restrictedFields, forKey: .restrictedFields)
    try container.encode(self.indexConfigs, forKey: .indexConfigs)
    try container.encodeIfPresent(self.cmekSettings, forKey: .cmekSettings)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.logging.v2.LogBucket"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
