// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Describes a repository in which log entries are stored.
public struct LogBucket: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The resource name of the bucket.
  ///
  /// For example:
  ///
  ///   `projects/my-project/locations/global/buckets/my-bucket`
  ///
  /// For a list of supported locations, see [Supported
  /// Regions](https://cloud.google.com/logging/docs/region-support)
  ///
  /// For the location of `global` it is unspecified where log entries are
  /// actually stored.
  ///
  /// After a bucket has been created, the location cannot be changed.
  public var name: Swift.String = Swift.String()

  /// Describes this bucket.
  public var description: Swift.String = Swift.String()

  /// Output only. The creation timestamp of the bucket. This is not set for any
  /// of the default buckets.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The last update timestamp of the bucket.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Logs will be retained by default for this amount of time, after which they
  /// will automatically be deleted. The minimum retention period is 1 day. If
  /// this value is set to zero at bucket creation time, the default time of 30
  /// days will be used.
  public var retentionDays: Swift.Int32 = Swift.Int32()

  /// Whether the bucket is locked.
  ///
  /// The retention period on a locked bucket cannot be changed. Locked buckets
  /// may only be deleted if they are empty.
  public var locked: Swift.Bool = Swift.Bool()

  /// Output only. The bucket lifecycle state.
  public var lifecycleState: LifecycleState = LifecycleState()

  /// Whether log analytics is enabled for this bucket.
  ///
  /// Once enabled, log analytics features cannot be disabled.
  public var analyticsEnabled: Swift.Bool = Swift.Bool()

  /// Log entry field paths that are denied access in this bucket.
  ///
  /// The following fields and their children are eligible: `textPayload`,
  /// `jsonPayload`, `protoPayload`, `httpRequest`, `labels`, `sourceLocation`.
  ///
  /// Restricting a repeated field will restrict all values. Adding a parent will
  /// block all child fields. (e.g. `foo.bar` will block `foo.bar.baz`)
  public var restrictedFields: [Swift.String] = []

  /// A list of indexed fields and related configuration data.
  public var indexConfigs: [IndexConfig] = []

  /// The CMEK settings of the log bucket. If present, new log entries written to
  /// this log bucket are encrypted using the CMEK key provided in this
  /// configuration. If a log bucket has CMEK settings, the CMEK settings cannot
  /// be disabled later by updating the log bucket. Changing the KMS key is
  /// allowed.
  public var cmekSettings: CmekSettings? = nil

  /// Initialize a new instance of `LogBucket`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LogBucket().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.logging.v2.LogBucket"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
