// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleApi
import GoogleCloudLoggingType
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// An individual entry in a log.
public struct LogEntry: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The resource name of the log to which this log entry belongs:
  ///
  ///     "projects/[PROJECT_ID]/logs/[LOG_ID]"
  ///     "organizations/[ORGANIZATION_ID]/logs/[LOG_ID]"
  ///     "billingAccounts/[BILLING_ACCOUNT_ID]/logs/[LOG_ID]"
  ///     "folders/[FOLDER_ID]/logs/[LOG_ID]"
  ///
  /// A project number may be used in place of PROJECT_ID. The project number is
  /// translated to its corresponding PROJECT_ID internally and the `log_name`
  /// field will contain PROJECT_ID in queries and exports.
  ///
  /// `[LOG_ID]` must be URL-encoded within `log_name`. Example:
  /// `"organizations/1234567890/logs/cloudresourcemanager.googleapis.com%2Factivity"`.
  ///
  /// `[LOG_ID]` must be less than 512 characters long and can only include the
  /// following characters: upper and lower case alphanumeric characters,
  /// forward-slash, underscore, hyphen, and period.
  ///
  /// For backward compatibility, if `log_name` begins with a forward-slash, such
  /// as `/projects/...`, then the log entry is ingested as usual, but the
  /// forward-slash is removed. Listing the log entry will not show the leading
  /// slash and filtering for a log name with a leading slash will never return
  /// any results.
  public var logName: Swift.String = Swift.String()

  /// Required. The monitored resource that produced this log entry.
  ///
  /// Example: a log entry that reports a database error would be associated with
  /// the monitored resource designating the particular database that reported
  /// the error.
  public var resource: GoogleApi.MonitoredResource? = nil

  /// Optional. The time the event described by the log entry occurred. This time
  /// is used to compute the log entry's age and to enforce the logs retention
  /// period. If this field is omitted in a new log entry, then Logging assigns
  /// it the current time. Timestamps have nanosecond accuracy, but trailing
  /// zeros in the fractional seconds might be omitted when the timestamp is
  /// displayed.
  ///
  /// Incoming log entries must have timestamps that don't exceed the
  /// [logs retention
  /// period](https://cloud.google.com/logging/quotas#logs_retention_periods) in
  /// the past, and that don't exceed 24 hours in the future. Log entries outside
  /// those time boundaries aren't ingested by Logging.
  public var timestamp: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time the log entry was received by Logging.
  public var receiveTimestamp: GoogleCloudWkt.Timestamp? = nil

  /// Optional. The severity of the log entry. The default value is
  /// `LogSeverity.DEFAULT`.
  public var severity: GoogleCloudLoggingType.LogSeverity = GoogleCloudLoggingType.LogSeverity()

  /// Optional. A unique identifier for the log entry. If you provide a value,
  /// then Logging considers other log entries in the same project, with the same
  /// `timestamp`, and with the same `insert_id` to be duplicates which are
  /// removed in a single query result. However, there are no guarantees of
  /// de-duplication in the export of logs.
  ///
  /// If the `insert_id` is omitted when writing a log entry, the Logging API
  /// assigns its own unique identifier in this field.
  ///
  /// In queries, the `insert_id` is also used to order log entries that have
  /// the same `log_name` and `timestamp` values.
  public var insertId: Swift.String = Swift.String()

  /// Optional. Information about the HTTP request associated with this log
  /// entry, if applicable.
  public var httpRequest: GoogleCloudLoggingType.HttpRequest? = nil

  /// Optional. A map of key, value pairs that provides additional information
  /// about the log entry. The labels can be user-defined or system-defined.
  ///
  /// User-defined labels are arbitrary key, value pairs that you can use to
  /// classify logs.
  ///
  /// System-defined labels are defined by GCP services for platform logs.
  /// They have two components - a service namespace component and the
  /// attribute name. For example: `compute.googleapis.com/resource_name`.
  ///
  /// Cloud Logging truncates label keys that exceed 512 B and label
  /// values that exceed 64 KB upon their associated log entry being
  /// written. The truncation is indicated by an ellipsis at the
  /// end of the character string.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. Information about an operation associated with the log entry, if
  /// applicable.
  public var operation: LogEntryOperation? = nil

  /// Optional. The REST resource name of the trace being written to
  /// [Cloud Trace](https://cloud.google.com/trace) in
  /// association with this log entry. For example, if your trace data is stored
  /// in the Cloud project "my-trace-project" and if the service that is creating
  /// the log entry receives a trace header that includes the trace ID "12345",
  /// then the service should use "projects/my-tracing-project/traces/12345".
  ///
  /// The `trace` field provides the link between logs and traces. By using
  /// this field, you can navigate from a log entry to a trace.
  public var trace: Swift.String = Swift.String()

  /// Optional. The ID of the [Cloud Trace](https://cloud.google.com/trace) span
  /// associated with the current operation in which the log is being written.
  /// For example, if a span has the REST resource name of
  /// "projects/some-project/traces/some-trace/spans/some-span-id", then the
  /// `span_id` field is "some-span-id".
  ///
  /// A
  /// [Span](https://cloud.google.com/trace/docs/reference/v2/rest/v2/projects.traces/batchWrite#Span)
  /// represents a single operation within a trace. Whereas a trace may involve
  /// multiple different microservices running on multiple different machines,
  /// a span generally corresponds to a single logical operation being performed
  /// in a single instance of a microservice on one specific machine. Spans
  /// are the nodes within the tree that is a trace.
  ///
  /// Applications that are [instrumented for
  /// tracing](https://cloud.google.com/trace/docs/setup) will generally assign a
  /// new, unique span ID on each incoming request. It is also common to create
  /// and record additional spans corresponding to internal processing elements
  /// as well as issuing requests to dependencies.
  ///
  /// The span ID is expected to be a 16-character, hexadecimal encoding of an
  /// 8-byte array and should not be zero. It should be unique within the trace
  /// and should, ideally, be generated in a manner that is uniformly random.
  ///
  /// Example values:
  ///
  ///   - `000000000000004a`
  ///   - `7a2190356c3fc94b`
  ///   - `0000f00300090021`
  ///   - `d39223e101960076`
  public var spanId: Swift.String = Swift.String()

  /// Optional. The sampling decision of the trace associated with the log entry.
  ///
  /// True means that the trace resource name in the `trace` field was sampled
  /// for storage in a trace backend. False means that the trace was not sampled
  /// for storage when this log entry was written, or the sampling decision was
  /// unknown at the time. A non-sampled `trace` value is still useful as a
  /// request correlation identifier. The default is False.
  public var traceSampled: Swift.Bool = Swift.Bool()

  /// Optional. Source code location information associated with the log entry,
  /// if any.
  public var sourceLocation: LogEntrySourceLocation? = nil

  /// Optional. Information indicating this LogEntry is part of a sequence of
  /// multiple log entries split from a single LogEntry.
  public var split: LogSplit? = nil

  /// The log entry payload, which can be one of multiple types.
  public var payload: OneOf_Payload? = nil

  /// Initialize a new instance of `LogEntry`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LogEntry().with { $0.logName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case logName = "logName"
    case resource = "resource"
    case protoPayload = "protoPayload"
    case textPayload = "textPayload"
    case jsonPayload = "jsonPayload"
    case timestamp = "timestamp"
    case receiveTimestamp = "receiveTimestamp"
    case severity = "severity"
    case insertId = "insertId"
    case httpRequest = "httpRequest"
    case labels = "labels"
    case operation = "operation"
    case trace = "trace"
    case spanId = "spanId"
    case traceSampled = "traceSampled"
    case sourceLocation = "sourceLocation"
    case split = "split"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.logName = try container.decode(Swift.String.self, forKey: .logName)
    self.resource = try container.decodeIfPresent(
      GoogleApi.MonitoredResource.self, forKey: .resource)
    self.timestamp = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .timestamp)
    self.receiveTimestamp = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .receiveTimestamp)
    self.severity = try container.decode(GoogleCloudLoggingType.LogSeverity.self, forKey: .severity)
    self.insertId = try container.decode(Swift.String.self, forKey: .insertId)
    self.httpRequest = try container.decodeIfPresent(
      GoogleCloudLoggingType.HttpRequest.self, forKey: .httpRequest)
    self.labels = try container.decode([Swift.String: Swift.String].self, forKey: .labels)
    self.operation = try container.decodeIfPresent(LogEntryOperation.self, forKey: .operation)
    self.trace = try container.decode(Swift.String.self, forKey: .trace)
    self.spanId = try container.decode(Swift.String.self, forKey: .spanId)
    self.traceSampled = try container.decode(Swift.Bool.self, forKey: .traceSampled)
    self.sourceLocation = try container.decodeIfPresent(
      LogEntrySourceLocation.self, forKey: .sourceLocation)
    self.split = try container.decodeIfPresent(LogSplit.self, forKey: .split)

    var payload: OneOf_Payload? = nil
    let payloadCheckAndSet = {
      if payload != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'payload'"))
      }
      payload = $0
    }
    if let protoPayload = try container.decodeIfPresent(
      GoogleCloudWkt.`Any`?.self, forKey: .protoPayload)
    {
      try payloadCheckAndSet(.protoPayload(protoPayload))
    }
    if let textPayload = try container.decodeIfPresent(Swift.String.self, forKey: .textPayload) {
      try payloadCheckAndSet(.textPayload(textPayload))
    }
    if let jsonPayload = try container.decodeIfPresent(
      GoogleCloudWkt.Struct?.self, forKey: .jsonPayload)
    {
      try payloadCheckAndSet(.jsonPayload(jsonPayload))
    }
    self.payload = payload
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.logName, forKey: .logName)
    try container.encode(self.resource, forKey: .resource)
    try container.encode(self.timestamp, forKey: .timestamp)
    try container.encode(self.receiveTimestamp, forKey: .receiveTimestamp)
    try container.encode(self.severity, forKey: .severity)
    try container.encode(self.insertId, forKey: .insertId)
    try container.encode(self.httpRequest, forKey: .httpRequest)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.operation, forKey: .operation)
    try container.encode(self.trace, forKey: .trace)
    try container.encode(self.spanId, forKey: .spanId)
    try container.encode(self.traceSampled, forKey: .traceSampled)
    try container.encode(self.sourceLocation, forKey: .sourceLocation)
    try container.encode(self.split, forKey: .split)

    if let choice = self.payload {
      switch choice {
      case .protoPayload(let value):
        try container.encode(value, forKey: .protoPayload)
      case .textPayload(let value):
        try container.encode(value, forKey: .textPayload)
      case .jsonPayload(let value):
        try container.encode(value, forKey: .jsonPayload)
      }
    }
  }

  /// The log entry payload, which can be one of multiple types.
  public enum OneOf_Payload: Codable, Equatable, Sendable {
    /// The log entry payload, represented as a protocol buffer. Some Google
    /// Cloud Platform services use this field for their log entry payloads.
    ///
    /// The following protocol buffer types are supported; user-defined types
    /// are not supported:
    ///
    ///   "type.googleapis.com/google.cloud.audit.AuditLog"
    ///   "type.googleapis.com/google.appengine.logging.v1.RequestLog"
    indirect case protoPayload(GoogleCloudWkt.`Any`?)
    /// The log entry payload, represented as a Unicode string (UTF-8).
    case textPayload(Swift.String)
    /// The log entry payload, represented as a structure that is
    /// expressed as a JSON object.
    indirect case jsonPayload(GoogleCloudWkt.Struct?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.logging.v2.LogEntry"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
