// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleApi
import GoogleCloudWkt
import GoogleLongRunning
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class LoggingServiceV2Logging: LoggingServiceV2Stub {
    let inner: any LoggingServiceV2Stub
    let logger: Logger

    public init(_ inner: any LoggingServiceV2Stub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-logging-v2"
      logger[metadataKey: "gcp.client.service"] = "logging"
      logger[metadataKey: "gcp.experimental.swift.client"] = "LoggingServiceV2"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func deleteLog(
      request: DeleteLogRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteLog",
        action: { (r: DeleteLogRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteLog(request: r, options: o)
        })
    }

    public func writeLogEntries(
      request: WriteLogEntriesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.WriteLogEntriesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "writeLogEntries",
        action: {
          (r: WriteLogEntriesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLoggingV2.WriteLogEntriesResponse
          in
          return try await self.inner.writeLogEntries(request: r, options: o)
        })
    }

    public func listLogEntries(
      request: ListLogEntriesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.ListLogEntriesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLogEntries",
        action: {
          (r: ListLogEntriesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLoggingV2.ListLogEntriesResponse
          in
          return try await self.inner.listLogEntries(request: r, options: o)
        })
    }

    public func listMonitoredResourceDescriptors(
      request: ListMonitoredResourceDescriptorsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.ListMonitoredResourceDescriptorsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listMonitoredResourceDescriptors",
        action: {
          (r: ListMonitoredResourceDescriptorsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudLoggingV2.ListMonitoredResourceDescriptorsResponse
          in
          return try await self.inner.listMonitoredResourceDescriptors(request: r, options: o)
        })
    }

    public func listLogs(
      request: ListLogsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.ListLogsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLogs",
        action: {
          (r: ListLogsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLoggingV2.ListLogsResponse
          in
          return try await self.inner.listLogs(request: r, options: o)
        })
    }

    public func tailLogEntries(
      request: TailLogEntriesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.TailLogEntriesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "tailLogEntries",
        action: {
          (r: TailLogEntriesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLoggingV2.TailLogEntriesResponse
          in
          return try await self.inner.tailLogEntries(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOperation",
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
