// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Additional information used to correlate multiple log entries. Used when a
/// single LogEntry would exceed the Google Cloud Logging size limit and is
/// split across multiple log entries.
public struct LogSplit: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// A globally unique identifier for all log entries in a sequence of split log
  /// entries. All log entries with the same |LogSplit.uid| are assumed to be
  /// part of the same sequence of split log entries.
  public var uid: Swift.String = Swift.String()

  /// The index of this LogEntry in the sequence of split log entries. Log
  /// entries are given |index| values 0, 1, ..., n-1 for a sequence of n log
  /// entries.
  public var index: Swift.Int32 = Swift.Int32()

  /// The total number of log entries that the original LogEntry was split into.
  public var totalSplits: Swift.Int32 = Swift.Int32()

  /// Initialize a new instance of `LogSplit`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LogSplit().with { $0.uid = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.logging.v2.LogSplit"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
