// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Describes a view over log entries in a bucket.
public struct LogView: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The resource name of the view.
  ///
  /// For example:
  ///
  ///   `projects/my-project/locations/global/buckets/my-bucket/views/my-view`
  public var name: Swift.String = Swift.String()

  /// Describes this view.
  public var description: Swift.String = Swift.String()

  /// Output only. The creation timestamp of the view.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The last update timestamp of the view.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Filter that restricts which log entries in a bucket are visible in this
  /// view.
  ///
  /// Filters are restricted to be a logical AND of ==/!= of any of the
  /// following:
  ///
  ///   - originating project/folder/organization/billing account.
  ///   - resource type
  ///   - log id
  ///
  /// For example:
  ///
  ///   SOURCE("projects/myproject") AND resource.type = "gce_instance"
  ///                                AND LOG_ID("stdout")
  public var filter: Swift.String = Swift.String()

  /// Initialize a new instance of `LogView`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LogView().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.logging.v2.LogView"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
