// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongRunning
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class MetricsServiceV2Logging: MetricsServiceV2Stub {
    let inner: any MetricsServiceV2Stub
    let logger: Logger

    public init(_ inner: any MetricsServiceV2Stub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-logging-v2"
      logger[metadataKey: "gcp.client.service"] = "logging"
      logger[metadataKey: "gcp.experimental.swift.client"] = "MetricsServiceV2"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listLogMetrics(
      request: ListLogMetricsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.ListLogMetricsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLogMetrics",
        action: {
          (r: ListLogMetricsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLoggingV2.ListLogMetricsResponse
          in
          return try await self.inner.listLogMetrics(request: r, options: o)
        })
    }

    public func getLogMetric(
      request: GetLogMetricRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.LogMetric {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLogMetric",
        action: {
          (r: GetLogMetricRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLoggingV2.LogMetric
          in
          return try await self.inner.getLogMetric(request: r, options: o)
        })
    }

    public func createLogMetric(
      request: CreateLogMetricRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.LogMetric {
      try await self._intercept(
        request: request,
        options: options,
        name: "createLogMetric",
        action: {
          (r: CreateLogMetricRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLoggingV2.LogMetric
          in
          return try await self.inner.createLogMetric(request: r, options: o)
        })
    }

    public func updateLogMetric(
      request: UpdateLogMetricRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLoggingV2.LogMetric {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateLogMetric",
        action: {
          (r: UpdateLogMetricRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLoggingV2.LogMetric
          in
          return try await self.inner.updateLogMetric(request: r, options: o)
        })
    }

    public func deleteLogMetric(
      request: DeleteLogMetricRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteLogMetric",
        action: {
          (r: DeleteLogMetricRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteLogMetric(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOperation",
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
