// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Describes the settings associated with a project, folder, organization,
/// billing account, or flexible resource.
public struct Settings: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The resource name of the settings.
  public var name: Swift.String = Swift.String()

  /// Optional. The resource name for the configured Cloud KMS key.
  ///
  /// KMS key name format:
  ///
  ///     "projects/[PROJECT_ID]/locations/[LOCATION]/keyRings/[KEYRING]/cryptoKeys/[KEY]"
  ///
  /// For example:
  ///
  ///   `"projects/my-project/locations/us-central1/keyRings/my-ring/cryptoKeys/my-key"`
  ///
  ///
  ///
  /// To enable CMEK for the Log Router, set this field to a valid
  /// `kms_key_name` for which the associated service account has the required
  /// `roles/cloudkms.cryptoKeyEncrypterDecrypter` role assigned for the key.
  ///
  /// The Cloud KMS key used by the Log Router can be updated by changing the
  /// `kms_key_name` to a new valid key name. Encryption operations that are in
  /// progress will be completed with the key that was in use when they started.
  /// Decryption operations will be completed using the key that was used at the
  /// time of encryption unless access to that key has been revoked.
  ///
  /// To disable CMEK for the Log Router, set this field to an empty string.
  ///
  /// See [Enabling CMEK for Log
  /// Router](https://cloud.google.com/logging/docs/routing/managed-encryption)
  /// for more information.
  public var kmsKeyName: Swift.String = Swift.String()

  /// Output only. The service account that will be used by the Log Router to
  /// access your Cloud KMS key.
  ///
  /// Before enabling CMEK for Log Router, you must first assign the role
  /// `roles/cloudkms.cryptoKeyEncrypterDecrypter` to the service account that
  /// the Log Router will use to access your Cloud KMS key. Use
  /// [GetSettings][google.logging.v2.ConfigServiceV2.GetSettings] to
  /// obtain the service account ID.
  ///
  /// See [Enabling CMEK for Log
  /// Router](https://cloud.google.com/logging/docs/routing/managed-encryption)
  /// for more information.
  ///
  /// [google.logging.v2.ConfigServiceV2.GetSettings]: <doc:ConfigServiceV2Client/getSettings(request:options:)>
  public var kmsServiceAccountId: Swift.String = Swift.String()

  /// Optional. The Cloud region that will be used for _Default and _Required log
  /// buckets for newly created projects and folders. For example `europe-west1`.
  /// This setting does not affect the location of custom log buckets.
  public var storageLocation: Swift.String = Swift.String()

  /// Optional. If set to true, the _Default sink in newly created projects and
  /// folders will created in a disabled state. This can be used to automatically
  /// disable log ingestion if there is already an aggregated sink configured in
  /// the hierarchy. The _Default sink can be re-enabled manually if needed.
  public var disableDefaultSink: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `Settings`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Settings().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.logging.v2.Settings"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
