// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// The parameters to `UpdateExclusion`.
public struct UpdateExclusionRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The resource name of the exclusion to update:
  ///
  ///     "projects/[PROJECT_ID]/exclusions/[EXCLUSION_ID]"
  ///     "organizations/[ORGANIZATION_ID]/exclusions/[EXCLUSION_ID]"
  ///     "billingAccounts/[BILLING_ACCOUNT_ID]/exclusions/[EXCLUSION_ID]"
  ///     "folders/[FOLDER_ID]/exclusions/[EXCLUSION_ID]"
  ///
  /// For example:
  ///
  ///   `"projects/my-project/exclusions/my-exclusion"`
  public var name: Swift.String = Swift.String()

  /// Required. New values for the existing exclusion. Only the fields specified
  /// in `update_mask` are relevant.
  public var exclusion: LogExclusion? = nil

  /// Required. A non-empty list of fields to change in the existing exclusion.
  /// New values for the fields are taken from the corresponding fields in the
  /// [LogExclusion][google.logging.v2.LogExclusion] included in this request.
  /// Fields not mentioned in `update_mask` are not changed and are ignored in
  /// the request.
  ///
  /// For example, to change the filter and description of an exclusion,
  /// specify an `update_mask` of `"filter,description"`.
  ///
  /// [google.logging.v2.LogExclusion]: <doc:LogExclusion>
  public var updateMask: GoogleWKT.FieldMask? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `UpdateExclusionRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdateExclusionRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let exclusion = CodingKeys(stringValue: "exclusion")
    static let updateMask = CodingKeys(stringValue: "updateMask")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "exclusion",
      "updateMask",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.exclusion = try container.decodeIfPresent(LogExclusion.self, forKey: .exclusion)
    self.updateMask = try container.decodeIfPresent(GoogleWKT.FieldMask.self, forKey: .updateMask)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.exclusion, forKey: .exclusion)
    try container.encodeIfPresent(self.updateMask, forKey: .updateMask)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.logging.v2.UpdateExclusionRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
