// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleRpc
@_spi(GoogleCloudInternal) import GoogleWKT

/// Error details for WriteLogEntries with partial success.
public struct WriteLogEntriesPartialErrors: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// When `WriteLogEntriesRequest.partial_success` is true, records the error
  /// status for entries that were not written due to a permanent error, keyed
  /// by the entry's zero-based index in `WriteLogEntriesRequest.entries`.
  ///
  /// Failed requests for which no entries are written will not include
  /// per-entry errors.
  public var logEntryErrors: [Swift.Int32: GoogleRpc.Status] = [:]

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `WriteLogEntriesPartialErrors`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = WriteLogEntriesPartialErrors().with { $0.logEntryErrors = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let logEntryErrors = CodingKeys(stringValue: "logEntryErrors")

    static let _knownKeys: Set<Swift.String> = [
      "logEntryErrors"
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let stringKeyed = try container.decodeIfPresent(
      [Swift.String: GoogleRpc.Status].self, forKey: .logEntryErrors)
    {
      let tuples = try stringKeyed.lazy.map {
        (key, value) throws -> (Swift.Int32, GoogleRpc.Status) in
        guard let newKey = Swift.Int32(key) else {
          throw DecodingError.typeMismatch(
            Swift.Int32.self,
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Incorrect type for map key 'logEntryErrors'"))
        }
        return (newKey, value)
      }
      self.logEntryErrors = Dictionary(uniqueKeysWithValues: tuples)
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    do {
      let stringKeyed = Dictionary(
        uniqueKeysWithValues: self.logEntryErrors.lazy.map { (Swift.String($0), $1) }
      )
      try container.encode(stringKeyed, forKey: .logEntryErrors)
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.logging.v2.WriteLogEntriesPartialErrors"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
