// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongrunning
import GoogleRpc
import GoogleCloudGax

extension Clients {
  final class ConfigServiceV2Retry: ConfigServiceV2Stub {
    let inner: any ConfigServiceV2Stub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any ConfigServiceV2Stub, options: GoogleCloudGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func listBuckets(
      request: ListBucketsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLoggingV2.ListBucketsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListBucketsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLoggingV2.ListBucketsResponse
          in
          return try await self.inner.listBuckets(request: r, options: o)
        })
    }

    public func getBucket(
      request: GetBucketRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLoggingV2.LogBucket {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetBucketRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLoggingV2.LogBucket
          in
          return try await self.inner.getBucket(request: r, options: o)
        })
    }

    public func createBucketAsync(
      request: CreateBucketRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateBucketRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongrunning.Operation
          in
          return try await self.inner.createBucketAsync(request: r, options: o)
        })
    }

    public func updateBucketAsync(
      request: UpdateBucketRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateBucketRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongrunning.Operation
          in
          return try await self.inner.updateBucketAsync(request: r, options: o)
        })
    }

    public func createBucket(
      request: CreateBucketRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLoggingV2.LogBucket {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateBucketRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLoggingV2.LogBucket
          in
          return try await self.inner.createBucket(request: r, options: o)
        })
    }

    public func updateBucket(
      request: UpdateBucketRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLoggingV2.LogBucket {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateBucketRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLoggingV2.LogBucket
          in
          return try await self.inner.updateBucket(request: r, options: o)
        })
    }

    public func deleteBucket(
      request: DeleteBucketRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: { (r: DeleteBucketRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteBucket(request: r, options: o)
        })
    }

    public func undeleteBucket(
      request: UndeleteBucketRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UndeleteBucketRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.undeleteBucket(request: r, options: o)
        })
    }

    public func listViews(
      request: ListViewsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLoggingV2.ListViewsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListViewsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLoggingV2.ListViewsResponse
          in
          return try await self.inner.listViews(request: r, options: o)
        })
    }

    public func getView(
      request: GetViewRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLoggingV2.LogView {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetViewRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLoggingV2.LogView
          in
          return try await self.inner.getView(request: r, options: o)
        })
    }

    public func createView(
      request: CreateViewRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLoggingV2.LogView {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateViewRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLoggingV2.LogView
          in
          return try await self.inner.createView(request: r, options: o)
        })
    }

    public func updateView(
      request: UpdateViewRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLoggingV2.LogView {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateViewRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLoggingV2.LogView
          in
          return try await self.inner.updateView(request: r, options: o)
        })
    }

    public func deleteView(
      request: DeleteViewRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: { (r: DeleteViewRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteView(request: r, options: o)
        })
    }

    public func listSinks(
      request: ListSinksRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLoggingV2.ListSinksResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListSinksRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLoggingV2.ListSinksResponse
          in
          return try await self.inner.listSinks(request: r, options: o)
        })
    }

    public func getSink(
      request: GetSinkRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLoggingV2.LogSink {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetSinkRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLoggingV2.LogSink
          in
          return try await self.inner.getSink(request: r, options: o)
        })
    }

    public func createSink(
      request: CreateSinkRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLoggingV2.LogSink {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateSinkRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLoggingV2.LogSink
          in
          return try await self.inner.createSink(request: r, options: o)
        })
    }

    public func updateSink(
      request: UpdateSinkRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLoggingV2.LogSink {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: UpdateSinkRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLoggingV2.LogSink
          in
          return try await self.inner.updateSink(request: r, options: o)
        })
    }

    public func deleteSink(
      request: DeleteSinkRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: { (r: DeleteSinkRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteSink(request: r, options: o)
        })
    }

    public func createLink(
      request: CreateLinkRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateLinkRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongrunning.Operation
          in
          return try await self.inner.createLink(request: r, options: o)
        })
    }

    public func deleteLink(
      request: DeleteLinkRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteLinkRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongrunning.Operation
          in
          return try await self.inner.deleteLink(request: r, options: o)
        })
    }

    public func listLinks(
      request: ListLinksRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLoggingV2.ListLinksResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListLinksRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLoggingV2.ListLinksResponse
          in
          return try await self.inner.listLinks(request: r, options: o)
        })
    }

    public func getLink(
      request: GetLinkRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLoggingV2.Link {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetLinkRequest, o: GoogleCloudGax.RequestOptions) async throws -> GoogleLoggingV2.Link
          in
          return try await self.inner.getLink(request: r, options: o)
        })
    }

    public func listExclusions(
      request: ListExclusionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLoggingV2.ListExclusionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListExclusionsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLoggingV2.ListExclusionsResponse
          in
          return try await self.inner.listExclusions(request: r, options: o)
        })
    }

    public func getExclusion(
      request: GetExclusionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLoggingV2.LogExclusion {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetExclusionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLoggingV2.LogExclusion
          in
          return try await self.inner.getExclusion(request: r, options: o)
        })
    }

    public func createExclusion(
      request: CreateExclusionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLoggingV2.LogExclusion {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateExclusionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLoggingV2.LogExclusion
          in
          return try await self.inner.createExclusion(request: r, options: o)
        })
    }

    public func updateExclusion(
      request: UpdateExclusionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLoggingV2.LogExclusion {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateExclusionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLoggingV2.LogExclusion
          in
          return try await self.inner.updateExclusion(request: r, options: o)
        })
    }

    public func deleteExclusion(
      request: DeleteExclusionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteExclusionRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteExclusion(request: r, options: o)
        })
    }

    public func getCmekSettings(
      request: GetCmekSettingsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLoggingV2.CmekSettings {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetCmekSettingsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLoggingV2.CmekSettings
          in
          return try await self.inner.getCmekSettings(request: r, options: o)
        })
    }

    public func updateCmekSettings(
      request: UpdateCmekSettingsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLoggingV2.CmekSettings {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateCmekSettingsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLoggingV2.CmekSettings
          in
          return try await self.inner.updateCmekSettings(request: r, options: o)
        })
    }

    public func getSettings(
      request: GetSettingsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLoggingV2.Settings {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetSettingsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLoggingV2.Settings
          in
          return try await self.inner.getSettings(request: r, options: o)
        })
    }

    public func updateSettings(
      request: UpdateSettingsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLoggingV2.Settings {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateSettingsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLoggingV2.Settings
          in
          return try await self.inner.updateSettings(request: r, options: o)
        })
    }

    public func copyLogEntries(
      request: CopyLogEntriesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CopyLogEntriesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongrunning.Operation
          in
          return try await self.inner.copyLogEntries(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongrunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongrunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongrunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongrunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongrunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongrunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongrunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
