// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// LogBucket lifecycle states.
public enum LifecycleState: Codable, Equatable, Sendable {
  /// Unspecified state. This is only used/useful for distinguishing unset
  /// values.
  case unspecified
  /// The normal and active state.
  case active
  /// The resource has been marked for deletion by the user. For some resources
  /// (e.g. buckets), this can be reversed by an un-delete operation.
  case deleteRequested
  /// The resource has been marked for an update by the user. It will remain in
  /// this state until the update is complete.
  case updating
  /// The resource has been marked for creation by the user. It will remain in
  /// this state until the creation is complete.
  case creating
  /// The resource is in an INTERNAL error state.
  case failed
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .active: return 1
    case .deleteRequested: return 2
    case .updating: return 3
    case .creating: return 4
    case .failed: return 5
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "LIFECYCLE_STATE_UNSPECIFIED"
    case .active: return "ACTIVE"
    case .deleteRequested: return "DELETE_REQUESTED"
    case .updating: return "UPDATING"
    case .creating: return "CREATING"
    case .failed: return "FAILED"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:LifecycleState/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "LIFECYCLE_STATE_UNSPECIFIED": self = .unspecified
    case "ACTIVE": self = .active
    case "DELETE_REQUESTED": self = .deleteRequested
    case "UPDATING": self = .updating
    case "CREATING": self = .creating
    case "FAILED": self = .failed
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:LifecycleState/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .active
    case 2: self = .deleteRequested
    case 3: self = .updating
    case 4: self = .creating
    case 5: self = .failed
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode(0)
    case .active: return try container.encode(1)
    case .deleteRequested: return try container.encode(2)
    case .updating: return try container.encode(3)
    case .creating: return try container.encode(4)
    case .failed: return try container.encode(5)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
