// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleApi
import GoogleCloudWkt
import GoogleLongrunning
import GoogleCloudGax

extension Clients {
  final class LoggingServiceV2Retry: LoggingServiceV2Stub {
    let inner: any LoggingServiceV2Stub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any LoggingServiceV2Stub, options: GoogleCloudGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func deleteLog(
      request: DeleteLogRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: { (r: DeleteLogRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteLog(request: r, options: o)
        })
    }

    public func writeLogEntries(
      request: WriteLogEntriesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLoggingV2.WriteLogEntriesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: WriteLogEntriesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLoggingV2.WriteLogEntriesResponse
          in
          return try await self.inner.writeLogEntries(request: r, options: o)
        })
    }

    public func listLogEntries(
      request: ListLogEntriesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLoggingV2.ListLogEntriesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ListLogEntriesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLoggingV2.ListLogEntriesResponse
          in
          return try await self.inner.listLogEntries(request: r, options: o)
        })
    }

    public func listMonitoredResourceDescriptors(
      request: ListMonitoredResourceDescriptorsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLoggingV2.ListMonitoredResourceDescriptorsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListMonitoredResourceDescriptorsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLoggingV2.ListMonitoredResourceDescriptorsResponse
          in
          return try await self.inner.listMonitoredResourceDescriptors(request: r, options: o)
        })
    }

    public func listLogs(
      request: ListLogsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLoggingV2.ListLogsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListLogsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLoggingV2.ListLogsResponse
          in
          return try await self.inner.listLogs(request: r, options: o)
        })
    }

    public func tailLogEntries(
      request: TailLogEntriesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLoggingV2.TailLogEntriesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: TailLogEntriesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLoggingV2.TailLogEntriesResponse
          in
          return try await self.inner.tailLogEntries(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongrunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongrunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongrunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongrunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongrunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongrunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongrunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
