// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Describes a sink used to export log entries to one of the following
/// destinations in any project: a Cloud Storage bucket, a BigQuery dataset, a
/// Pub/Sub topic or a Cloud Logging log bucket. A logs filter controls which log
/// entries are exported. The sink must be created within a project,
/// organization, billing account, or folder.
public struct LogSink: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The client-assigned sink identifier, unique within the project.
  ///
  /// For example: `"my-syslog-errors-to-pubsub"`. Sink identifiers are limited
  /// to 100 characters and can include only the following characters: upper and
  /// lower-case alphanumeric characters, underscores, hyphens, and periods.
  /// First character has to be alphanumeric.
  public var name: Swift.String = Swift.String()

  /// Required. The export destination:
  ///
  ///     "storage.googleapis.com/[GCS_BUCKET]"
  ///     "bigquery.googleapis.com/projects/[PROJECT_ID]/datasets/[DATASET]"
  ///     "pubsub.googleapis.com/projects/[PROJECT_ID]/topics/[TOPIC_ID]"
  ///
  /// The sink's `writer_identity`, set when the sink is created, must have
  /// permission to write to the destination or else the log entries are not
  /// exported. For more information, see
  /// [Exporting Logs with
  /// Sinks](https://cloud.google.com/logging/docs/api/tasks/exporting-logs).
  public var destination: Swift.String = Swift.String()

  /// Optional. An [advanced logs
  /// filter](https://cloud.google.com/logging/docs/view/advanced-queries). The
  /// only exported log entries are those that are in the resource owning the
  /// sink and that match the filter.
  ///
  /// For example:
  ///
  ///   `logName="projects/[PROJECT_ID]/logs/[LOG_ID]" AND severity>=ERROR`
  public var filter: Swift.String = Swift.String()

  /// Optional. A description of this sink.
  ///
  /// The maximum length of the description is 8000 characters.
  public var description: Swift.String = Swift.String()

  /// Optional. If set to true, then this sink is disabled and it does not export
  /// any log entries.
  public var disabled: Swift.Bool = Swift.Bool()

  /// Optional. Log entries that match any of these exclusion filters will not be
  /// exported.
  ///
  /// If a log entry is matched by both `filter` and one of `exclusion_filters`
  /// it will not be exported.
  public var exclusions: [LogExclusion] = []

  /// Deprecated. This field is unused.
  @available(*, deprecated)
  public var outputVersionFormat: LogSink.VersionFormat = LogSink.VersionFormat()

  /// Output only. An IAM identity&mdash;a service account or group&mdash;under
  /// which Cloud Logging writes the exported log entries to the sink's
  /// destination. This field is either set by specifying
  /// `custom_writer_identity` or set automatically by
  /// [sinks.create][google.logging.v2.ConfigServiceV2.CreateSink] and
  /// [sinks.update][google.logging.v2.ConfigServiceV2.UpdateSink] based on the
  /// value of `unique_writer_identity` in those methods.
  ///
  /// Until you grant this identity write-access to the destination, log entry
  /// exports from this sink will fail. For more information, see [Granting
  /// Access for a
  /// Resource](https://cloud.google.com/iam/docs/granting-roles-to-service-accounts#granting_access_to_a_service_account_for_a_resource).
  /// Consult the destination service's documentation to determine the
  /// appropriate IAM roles to assign to the identity.
  ///
  /// Sinks that have a destination that is a log bucket in the same project as
  /// the sink cannot have a writer_identity and no additional permissions are
  /// required.
  ///
  /// [google.logging.v2.ConfigServiceV2.CreateSink]: <doc:ConfigServiceV2/createSink(request:)>
  /// [google.logging.v2.ConfigServiceV2.UpdateSink]: <doc:ConfigServiceV2/updateSink(request:)>
  public var writerIdentity: Swift.String = Swift.String()

  /// Optional. This field applies only to sinks owned by organizations and
  /// folders. If the field is false, the default, only the logs owned by the
  /// sink's parent resource are available for export. If the field is true, then
  /// log entries from all the projects, folders, and billing accounts contained
  /// in the sink's parent resource are also available for export. Whether a
  /// particular log entry from the children is exported depends on the sink's
  /// filter expression.
  ///
  /// For example, if this field is true, then the filter
  /// `resource.type=gce_instance` would export all Compute Engine VM instance
  /// log entries from all projects in the sink's parent.
  ///
  /// To only export entries from certain child projects, filter on the project
  /// part of the log name:
  ///
  ///   logName:("projects/test-project1/" OR "projects/test-project2/") AND
  ///   resource.type=gce_instance
  public var includeChildren: Swift.Bool = Swift.Bool()

  /// Output only. The creation timestamp of the sink.
  ///
  /// This field may not be present for older sinks.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The last update timestamp of the sink.
  ///
  /// This field may not be present for older sinks.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Destination dependent options.
  public var options: OneOf_Options? = nil

  /// Initialize a new instance of `LogSink`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LogSink().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case name = "name"
    case destination = "destination"
    case filter = "filter"
    case description = "description"
    case disabled = "disabled"
    case exclusions = "exclusions"
    case outputVersionFormat = "outputVersionFormat"
    case writerIdentity = "writerIdentity"
    case includeChildren = "includeChildren"
    case bigqueryOptions = "bigqueryOptions"
    case createTime = "createTime"
    case updateTime = "updateTime"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.destination = try container.decode(Swift.String.self, forKey: .destination)
    self.filter = try container.decode(Swift.String.self, forKey: .filter)
    self.description = try container.decode(Swift.String.self, forKey: .description)
    self.disabled = try container.decode(Swift.Bool.self, forKey: .disabled)
    self.exclusions = try container.decode([LogExclusion].self, forKey: .exclusions)
    self.outputVersionFormat = try container.decode(
      LogSink.VersionFormat.self, forKey: .outputVersionFormat)
    self.writerIdentity = try container.decode(Swift.String.self, forKey: .writerIdentity)
    self.includeChildren = try container.decode(Swift.Bool.self, forKey: .includeChildren)
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .updateTime)

    var options: OneOf_Options? = nil
    let optionsCheckAndSet = {
      if options != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'options'"))
      }
      options = $0
    }
    if let bigqueryOptions = try container.decodeIfPresent(
      BigQueryOptions?.self, forKey: .bigqueryOptions)
    {
      try optionsCheckAndSet(.bigqueryOptions(bigqueryOptions))
    }
    self.options = options
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.destination, forKey: .destination)
    try container.encode(self.filter, forKey: .filter)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.disabled, forKey: .disabled)
    try container.encode(self.exclusions, forKey: .exclusions)
    try container.encode(self.outputVersionFormat, forKey: .outputVersionFormat)
    try container.encode(self.writerIdentity, forKey: .writerIdentity)
    try container.encode(self.includeChildren, forKey: .includeChildren)
    try container.encode(self.createTime, forKey: .createTime)
    try container.encode(self.updateTime, forKey: .updateTime)

    if let choice = self.options {
      switch choice {
      case .bigqueryOptions(let value):
        try container.encode(value, forKey: .bigqueryOptions)
      }
    }
  }

  /// Deprecated. This is unused.
  public enum VersionFormat: Codable, Equatable, Sendable {
    /// An unspecified format version that will default to V2.
    case unspecified
    /// `LogEntry` version 2 format.
    case v2
    /// `LogEntry` version 1 format.
    case v1
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .v2: return 1
      case .v1: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "VERSION_FORMAT_UNSPECIFIED"
      case .v2: return "V2"
      case .v1: return "V1"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "VERSION_FORMAT_UNSPECIFIED": self = .unspecified
      case "V2": self = .v2
      case "V1": self = .v1
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .v2
      case 2: self = .v1
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .v2: return try container.encode(1)
      case .v1: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Destination dependent options.
  public enum OneOf_Options: Codable, Equatable, Sendable {
    /// Optional. Options that affect sinks exporting data to BigQuery.
    indirect case bigqueryOptions(BigQueryOptions?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.logging.v2.LogSink"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
